// Generated by gencpp from file cam/ImageSrv.msg
// DO NOT EDIT!


#ifndef CAM_MESSAGE_IMAGESRV_H
#define CAM_MESSAGE_IMAGESRV_H

#include <ros/service_traits.h>


#include <cam/ImageSrvRequest.h>
#include <cam/ImageSrvResponse.h>


namespace cam
{

struct ImageSrv
{

typedef ImageSrvRequest Request;
typedef ImageSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageSrv
} // namespace cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cam::ImageSrv > {
  static const char* value()
  {
    return "ba55116f263d40ea8759822097ad63d4";
  }

  static const char* value(const ::cam::ImageSrv&) { return value(); }
};

template<>
struct DataType< ::cam::ImageSrv > {
  static const char* value()
  {
    return "cam/ImageSrv";
  }

  static const char* value(const ::cam::ImageSrv&) { return value(); }
};


// service_traits::MD5Sum< ::cam::ImageSrvRequest> should match 
// service_traits::MD5Sum< ::cam::ImageSrv > 
template<>
struct MD5Sum< ::cam::ImageSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cam::ImageSrv >::value();
  }
  static const char* value(const ::cam::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::ImageSrvRequest> should match 
// service_traits::DataType< ::cam::ImageSrv > 
template<>
struct DataType< ::cam::ImageSrvRequest>
{
  static const char* value()
  {
    return DataType< ::cam::ImageSrv >::value();
  }
  static const char* value(const ::cam::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cam::ImageSrvResponse> should match 
// service_traits::MD5Sum< ::cam::ImageSrv > 
template<>
struct MD5Sum< ::cam::ImageSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cam::ImageSrv >::value();
  }
  static const char* value(const ::cam::ImageSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::ImageSrvResponse> should match 
// service_traits::DataType< ::cam::ImageSrv > 
template<>
struct DataType< ::cam::ImageSrvResponse>
{
  static const char* value()
  {
    return DataType< ::cam::ImageSrv >::value();
  }
  static const char* value(const ::cam::ImageSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAM_MESSAGE_IMAGESRV_H
